### ISSUE TITLE
Container in c++

### ISSUE THREAD

**Issue by vsoch** [cesarvr/container#1]
hey @cesarvr ! 

I love your post! I've worked with containers for a bit, and it's really helping me get a better understanding of what's going on. The page is also just lovely :)

Quick question - I'm learning C++ so I'm trying to do the same implementation, slightly modified with C++. I'm up to the "running programs" step but I think the clone call is off - the jail call (when it is cloned) never returns with success. Could you maybe give me some tips? What I have so far is here --> https://github.com/vsoch/container.  Thank you!

**Comment by cesarvr** [comment]
Hi @vsoch ,  

I'm glad you like it. About the clone syscall, I forgot to add this small function in the example:

```cpp

char* stack_memory() {
  const int stackSize = 65536;
  auto *stack = new (std::nothrow) char[stackSize];

  if (stack == nullptr) { 
    printf("Cannot allocate memory \n");
    exit(EXIT_FAILURE);
  }  

  return stack+stackSize;    //move the pointer to the end of the array because the stack grows backward. 
}

int main() {
 clone(jail, stack_memory(), SIGCHLD, 0);
 
 return 0; 
}
```
The **clone** function basically load the binary in memory, but it need some manual memory allocation for the executable to run. That function  **stack_memory** does just that, it allocate an arbitrary amount of memory and pass it back to **clone**.

If you need more info let me know. 
Cheers.

**Comment by vsoch** [comment]
that was it! I feel silly, I was google searching for that function and came up empty handed, so tried getting away with it set to NULL. We have... container!!

![image](https://user-images.githubusercontent.com/814322/47091988-002d6300-d1f4-11e8-9685-f35711f87663.png)


This is so incredibly cool!! I will definitely ping you if I have more questions, etc. Closing issue!
